/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dao.DAOException;
import dao.DAOManager;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import modelo.Catalogo;
import modelo.DetallePedidoProveedor;
import modelo.DetallePedidoProveedor.Id;
import modelo.ItemCatalogo;
import modelo.Material;
import modelo.PedidoProveedor;
import modelo.Proveedor;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author leori
 */
public class Compra extends javax.swing.JFrame {

    private final DAOManager manager;
    private MaterialEscasoTableModel model;
    private List<ItemCatalogo> listItemCatalogo = new ArrayList<>();
    int fila = 0;
    Object[][] datosTable = null;
    List<Object> datosComprar = new ArrayList<>();
    List<Material> datosComprarM = new ArrayList<>();
    List<Proveedor> proveedores = new ArrayList<>();
    Proveedor proveedorCompra;
    int mod;

    /**
     * Creates new form Compra
     *
     * @param manager
     * @throws dao.DAOException
     */
    public Compra(DAOManager manager, int mod) throws DAOException {
        initComponents();
        this.manager = manager;
        this.mod = mod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogRealizarPedido = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dialogRealizarPedidoOne = new javax.swing.JDialog();
        btnAtrasRPO = new javax.swing.JButton();
        btnSiguienteRPO = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableProveedoresxRubro = new javax.swing.JTable();
        btnPVC = new javax.swing.JButton();
        btnFerreteria = new javax.swing.JButton();
        btnElectricidad = new javax.swing.JButton();
        btnConstruccion = new javax.swing.JButton();
        btnPintureria = new javax.swing.JButton();
        btnVerCatalogos = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelRubro = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dialogRealizarPedidoTwo = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePedidoFinal = new javax.swing.JTable();
        txtProveedorRPT = new javax.swing.JTextField();
        txtDireccionRPT = new javax.swing.JTextField();
        txtTelefonoRPT = new javax.swing.JTextField();
        btnAtrasRPT = new javax.swing.JButton();
        btnGuardarRPT = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        dialogRecibirCatalgo = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtCuitRC = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccionP = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnAtrasRC = new javax.swing.JButton();
        btnAgregarTabla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItemCatalogo = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        dialogSucces = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        dialogSuccesPrint = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        dialogRecibirPedido = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        txtNumeroPedido = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnBuscarPedido = new javax.swing.JButton();
        btnAtrasRO = new javax.swing.JButton();
        txtInexistente = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAtrasC = new javax.swing.JButton();
        btnRealizarPedido = new javax.swing.JButton();
        btnRecibirPedido = new javax.swing.JButton();
        btnRecibirCatalogo = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();

        dialogRealizarPedido.setResizable(false);
        dialogRealizarPedido.getContentPane().setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 51, 102));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 51, 153));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        dialogRealizarPedido.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 80, 600, 350);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        dialogRealizarPedido.getContentPane().add(btnAtras);
        btnAtras.setBounds(60, 440, 59, 23);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        dialogRealizarPedido.getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(657, 440, 120, 23);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Realizar Pedido a Proveedor");
        dialogRealizarPedido.getContentPane().add(jLabel19);
        jLabel19.setBounds(210, 10, 340, 50);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        dialogRealizarPedido.getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 800, 520);

        dialogRealizarPedidoOne.setSize(new java.awt.Dimension(100, 25));
        dialogRealizarPedidoOne.getContentPane().setLayout(null);

        btnAtrasRPO.setText("Atras");
        btnAtrasRPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasRPOActionPerformed(evt);
            }
        });
        dialogRealizarPedidoOne.getContentPane().add(btnAtrasRPO);
        btnAtrasRPO.setBounds(70, 450, 59, 23);

        btnSiguienteRPO.setText("Siguiente");
        btnSiguienteRPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteRPOActionPerformed(evt);
            }
        });
        dialogRealizarPedidoOne.getContentPane().add(btnSiguienteRPO);
        btnSiguienteRPO.setBounds(670, 440, 100, 23);

        tableProveedoresxRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cuit", "Nombre", "Telefono", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableProveedoresxRubro);
        if (tableProveedoresxRubro.getColumnModel().getColumnCount() > 0) {
            tableProveedoresxRubro.getColumnModel().getColumn(0).setResizable(false);
            tableProveedoresxRubro.getColumnModel().getColumn(1).setResizable(false);
            tableProveedoresxRubro.getColumnModel().getColumn(3).setResizable(false);
        }

        dialogRealizarPedidoOne.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(150, 160, 470, 260);

        btnPVC.setText("PVC");
        btnPVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPVCActionPerformed(evt);
            }
        });
        dialogRealizarPedidoOne.getContentPane().add(btnPVC);
        btnPVC.setBounds(150, 90, 60, 23);

        btnFerreteria.setText("Ferreteria");
        btnFerreteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerreteriaActionPerformed(evt);
            }
        });
        dialogRealizarPedidoOne.getContentPane().add(btnFerreteria);
        btnFerreteria.setBounds(220, 90, 81, 23);

        btnElectricidad.setText("Electricidad");
        btnElectricidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElectricidadActionPerformed(evt);
            }
        });
        dialogRealizarPedidoOne.getContentPane().add(btnElectricidad);
        btnElectricidad.setBounds(320, 90, 87, 23);

        btnConstruccion.setText("Construccion");
        btnConstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstruccionActionPerformed(evt);
            }
        });
        dialogRealizarPedidoOne.getContentPane().add(btnConstruccion);
        btnConstruccion.setBounds(420, 90, 95, 23);

        btnPintureria.setText("Pintureria");
        btnPintureria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPintureriaActionPerformed(evt);
            }
        });
        dialogRealizarPedidoOne.getContentPane().add(btnPintureria);
        btnPintureria.setBounds(540, 90, 79, 23);

        btnVerCatalogos.setText("Ver Catalogo");
        btnVerCatalogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCatalogosActionPerformed(evt);
            }
        });
        dialogRealizarPedidoOne.getContentPane().add(btnVerCatalogos);
        btnVerCatalogos.setBounds(650, 230, 110, 23);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Realizar Pedido a Proveedor");
        dialogRealizarPedidoOne.getContentPane().add(jLabel26);
        jLabel26.setBounds(210, 10, 340, 50);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Seleccionar Rubro:");
        dialogRealizarPedidoOne.getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 60, 120, 15);

        labelRubro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelRubro.setForeground(new java.awt.Color(255, 255, 255));
        dialogRealizarPedidoOne.getContentPane().add(labelRubro);
        labelRubro.setBounds(270, 120, 190, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogRealizarPedidoOne.getContentPane().add(jLabel21);
        jLabel21.setBounds(0, -10, 800, 550);

        dialogRealizarPedidoTwo.getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pedido a Proveedor");
        dialogRealizarPedidoTwo.getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 10, 240, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Proveedor:");
        dialogRealizarPedidoTwo.getContentPane().add(jLabel12);
        jLabel12.setBounds(84, 54, 70, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Dirección: ");
        dialogRealizarPedidoTwo.getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 54, 70, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Telefono: ");
        dialogRealizarPedidoTwo.getContentPane().add(jLabel14);
        jLabel14.setBounds(499, 54, 70, 20);

        tablePedidoFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablePedidoFinal);

        dialogRealizarPedidoTwo.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(110, 100, 550, 340);

        txtProveedorRPT.setEditable(false);
        dialogRealizarPedidoTwo.getContentPane().add(txtProveedorRPT);
        txtProveedorRPT.setBounds(160, 50, 100, 25);

        txtDireccionRPT.setEditable(false);
        dialogRealizarPedidoTwo.getContentPane().add(txtDireccionRPT);
        txtDireccionRPT.setBounds(340, 50, 150, 25);

        txtTelefonoRPT.setEditable(false);
        dialogRealizarPedidoTwo.getContentPane().add(txtTelefonoRPT);
        txtTelefonoRPT.setBounds(560, 50, 100, 25);

        btnAtrasRPT.setText("Atras");
        btnAtrasRPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasRPTActionPerformed(evt);
            }
        });
        dialogRealizarPedidoTwo.getContentPane().add(btnAtrasRPT);
        btnAtrasRPT.setBounds(30, 470, 59, 23);

        btnGuardarRPT.setText("Guardar");
        btnGuardarRPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRPTActionPerformed(evt);
            }
        });
        dialogRealizarPedidoTwo.getContentPane().add(btnGuardarRPT);
        btnGuardarRPT.setBounds(690, 470, 90, 23);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogRealizarPedidoTwo.getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 0, 800, 530);

        dialogRecibirCatalgo.setSize(new java.awt.Dimension(800, 530));
        dialogRecibirCatalgo.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recibir Catalogo");
        dialogRecibirCatalgo.getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 20, 210, 29);

        txtCuitRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuitRCActionPerformed(evt);
            }
        });
        dialogRecibirCatalgo.getContentPane().add(txtCuitRC);
        txtCuitRC.setBounds(320, 70, 100, 25);

        btnBuscarProveedor.setText("Buscar");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });
        dialogRecibirCatalgo.getContentPane().add(btnBuscarProveedor);
        btnBuscarProveedor.setBounds(430, 70, 65, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cuit Proveedor:");
        dialogRecibirCatalgo.getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 70, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre: ");
        dialogRecibirCatalgo.getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 110, 60, 20);
        dialogRecibirCatalgo.getContentPane().add(txtNombreP);
        txtNombreP.setBounds(250, 110, 100, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion: ");
        dialogRecibirCatalgo.getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 110, 70, 20);
        dialogRecibirCatalgo.getContentPane().add(txtDireccionP);
        txtDireccionP.setBounds(420, 110, 150, 25);
        dialogRecibirCatalgo.getContentPane().add(jSeparator1);
        jSeparator1.setBounds(110, 144, 590, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Material:");
        dialogRecibirCatalgo.getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 166, 70, 20);
        dialogRecibirCatalgo.getContentPane().add(txtMaterial);
        txtMaterial.setBounds(90, 186, 100, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio:");
        dialogRecibirCatalgo.getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 234, 50, 20);
        dialogRecibirCatalgo.getContentPane().add(txtPrecio);
        txtPrecio.setBounds(90, 254, 100, 25);

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        dialogRecibirCatalgo.getContentPane().add(txtMarca);
        txtMarca.setBounds(90, 322, 100, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Marca:");
        dialogRecibirCatalgo.getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 302, 50, 20);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        dialogRecibirCatalgo.getContentPane().add(btnAgregar);
        btnAgregar.setBounds(690, 450, 71, 23);

        btnAtrasRC.setText("Atras");
        btnAtrasRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasRCActionPerformed(evt);
            }
        });
        dialogRecibirCatalgo.getContentPane().add(btnAtrasRC);
        btnAtrasRC.setBounds(50, 450, 59, 23);

        btnAgregarTabla.setText(">>>");
        btnAgregarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTablaActionPerformed(evt);
            }
        });
        dialogRecibirCatalgo.getContentPane().add(btnAgregarTabla);
        btnAgregarTabla.setBounds(244, 266, 57, 23);

        tableItemCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Material", "Precio", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableItemCatalogo);

        dialogRecibirCatalgo.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(340, 160, 360, 230);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogRecibirCatalgo.getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 0, 800, 530);

        dialogSucces.getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Exito en la Operacion");
        dialogSucces.getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 60, 160, 30);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        dialogSucces.getContentPane().add(jButton1);
        jButton1.setBounds(120, 110, 71, 23);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogSucces.getContentPane().add(jLabel25);
        jLabel25.setBounds(0, 0, 300, 200);

        dialogSuccesPrint.setResizable(false);
        dialogSuccesPrint.setSize(new java.awt.Dimension(300, 200));
        dialogSuccesPrint.getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Guardado con Exito");
        dialogSuccesPrint.getContentPane().add(jLabel15);
        jLabel15.setBounds(60, 70, 190, 30);

        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        dialogSuccesPrint.getContentPane().add(jButton2);
        jButton2.setBounds(100, 110, 100, 23);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogSuccesPrint.getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 300, 200);

        dialogRecibirPedido.setSize(new java.awt.Dimension(400, 300));
        dialogRecibirPedido.getContentPane().setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Recibir Pedido");
        dialogRecibirPedido.getContentPane().add(jLabel16);
        jLabel16.setBounds(100, 30, 190, 40);
        dialogRecibirPedido.getContentPane().add(txtNumeroPedido);
        txtNumeroPedido.setBounds(160, 130, 100, 25);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Número de Pedido:");
        dialogRecibirPedido.getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 130, 130, 30);

        btnBuscarPedido.setText("Buscar");
        btnBuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPedidoActionPerformed(evt);
            }
        });
        dialogRecibirPedido.getContentPane().add(btnBuscarPedido);
        btnBuscarPedido.setBounds(270, 130, 80, 23);

        btnAtrasRO.setText("Atras");
        btnAtrasRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasROActionPerformed(evt);
            }
        });
        dialogRecibirPedido.getContentPane().add(btnAtrasRO);
        btnAtrasRO.setBounds(40, 230, 59, 23);

        txtInexistente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtInexistente.setForeground(new java.awt.Color(255, 255, 255));
        dialogRecibirPedido.getContentPane().add(txtInexistente);
        txtInexistente.setBounds(140, 170, 100, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogRecibirPedido.getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 0, 400, 300);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Compra");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 40, 141, 44);

        btnAtrasC.setText("Atras");
        btnAtrasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasCActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtrasC);
        btnAtrasC.setBounds(40, 320, 59, 23);

        btnRealizarPedido.setBackground(new java.awt.Color(255, 255, 255));
        btnRealizarPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRealizarPedido.setForeground(new java.awt.Color(102, 102, 102));
        btnRealizarPedido.setText("Realizar Pedido");
        btnRealizarPedido.setBorder(null);
        btnRealizarPedido.setBorderPainted(false);
        btnRealizarPedido.setContentAreaFilled(false);
        btnRealizarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarPedido);
        btnRealizarPedido.setBounds(30, 180, 140, 40);

        btnRecibirPedido.setBackground(new java.awt.Color(255, 255, 255));
        btnRecibirPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRecibirPedido.setForeground(new java.awt.Color(102, 102, 102));
        btnRecibirPedido.setText("Recibir Pedido");
        btnRecibirPedido.setBorder(null);
        btnRecibirPedido.setBorderPainted(false);
        btnRecibirPedido.setContentAreaFilled(false);
        btnRecibirPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecibirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecibirPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecibirPedido);
        btnRecibirPedido.setBounds(180, 180, 140, 40);

        btnRecibirCatalogo.setBackground(java.awt.Color.white);
        btnRecibirCatalogo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRecibirCatalogo.setForeground(new java.awt.Color(102, 102, 102));
        btnRecibirCatalogo.setText("Recibir Catalogo");
        btnRecibirCatalogo.setBorder(null);
        btnRecibirCatalogo.setBorderPainted(false);
        btnRecibirCatalogo.setContentAreaFilled(false);
        btnRecibirCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecibirCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecibirCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecibirCatalogo);
        btnRecibirCatalogo.setBounds(330, 180, 140, 40);

        btnProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProveedor.setForeground(new java.awt.Color(102, 102, 102));
        btnProveedor.setText("Proveedores");
        btnProveedor.setBorder(null);
        btnProveedor.setBorderPainted(false);
        btnProveedor.setContentAreaFilled(false);
        btnProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedor);
        btnProveedor.setBounds(180, 240, 140, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(180, 240, 140, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        getContentPane().add(jTextArea2);
        jTextArea2.setBounds(30, 180, 140, 40);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setEnabled(false);
        getContentPane().add(jTextArea3);
        jTextArea3.setBounds(180, 180, 140, 40);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setEnabled(false);
        getContentPane().add(jTextArea4);
        jTextArea4.setBounds(330, 180, 140, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasCActionPerformed
        home ventHome;
        try {
            ventHome = new home(mod);
            ventHome.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnAtrasCActionPerformed

    private void btnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedidoActionPerformed
        // TODO add your handling code here:
        String[] columnas = new String[]{
            "Id Material",
            "Nombre",
            "Descripcion",
            "Stock Material",
            "Precio Unitario",
            "Rubro",
            "Seleccionar"};
        this.model = new MaterialEscasoTableModel(manager.getMaterialDAO());
        try {
            this.model.updateModel();
        } catch (DAOException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
        //this.jTable1.setModel(model);
        model.setDatoss();
        datosTable = model.getDatoss();
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(datosTable, columnas));
        this.jTable1.getColumnModel().getColumn(6).setCellEditor(new CellEditor());
        this.jTable1.getColumnModel().getColumn(6).setCellRenderer(new CellRender());

//        JScrollPane  scroll = new JScrollPane(jTable1);
//        jTable1.setPreferredScrollableViewportSize(new Dimension(500,70));
        dialogRealizarPedido.setVisible(true);
        dialogRealizarPedido.setTitle("Realizar Pedido a Proveedor");
        dialogRealizarPedido.setSize(800, 530);
        dialogRealizarPedido.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnRealizarPedidoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        dialogRealizarPedido.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        vtnProveedores vtnProveedores;
        vtnProveedores = new vtnProveedores(manager);
        vtnProveedores.setVisible(true);
        vtnProveedores.setSize(500, 400);
        vtnProveedores.setLocationRelativeTo(null);
//        this.dispose();

    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnRecibirCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecibirCatalogoActionPerformed
        // TODO add your handling code here:
        dialogRecibirCatalgo.setVisible(true);
        dialogRecibirCatalgo.setSize(800, 530);
        dialogRecibirCatalgo.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRecibirCatalogoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
        java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
        Catalogo catalogo = new Catalogo(sqlDate, Long.valueOf(txtCuitRC.getText()));

        try {
            manager.getCatalogoDAO().insertar(catalogo);
            Long id = catalogo.getIdCatalogo();
            int i = 0;
            for (ItemCatalogo item : listItemCatalogo) {
                ItemCatalogo itemNew = listItemCatalogo.get(i);
                itemNew.setIdCatalogo(id);
                listItemCatalogo.set(i, itemNew);
                manager.getItemCalatalogoDAO().insertar(item);
                i++;
            }
            fila = 1;

        } catch (DAOException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialogSucces.setVisible(true);
        dialogSucces.setSize(200, 200);
        dialogSucces.setLocationRelativeTo(null);
        dialogRecibirCatalgo.setVisible(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        // TODO add your handling code here:

        if (validaciones.isNumber(txtCuitRC.getText())) {
            Long cuitBuscado;
            cuitBuscado = Long.valueOf(txtCuitRC.getText());
            try {
                Proveedor p = manager.getProveedorDAO().obtener(cuitBuscado);
                if (p != null) {
                    txtNombreP.setText(p.getNombre());
                    txtNombreP.setEditable(false);
                    txtDireccionP.setText(p.getDireccion());
                    txtDireccionP.setEditable(false);
                } else {
                    vtnProveedores vtnProveedores;
                    vtnProveedores = new vtnProveedores(manager);
                    vtnProveedores.setVisible(true);
                    vtnProveedores.setSize(500, 400);
                    vtnProveedores.setResizable(false);
                }
            } catch (DAOException ex) {
                Logger.getLogger(vtnProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Ingrese un CUIT valido", "Information",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void txtCuitRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuitRCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuitRCActionPerformed

    private void btnAgregarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTablaActionPerformed
        // TODO add your handling code here:
        Long precio = Long.valueOf(txtPrecio.getText());
        String mat = txtMaterial.getText();
        String marca = txtMarca.getText();
        Long id = null;
        ItemCatalogo item = new ItemCatalogo(precio, mat, marca, id);
        listItemCatalogo.add(item);

        tableItemCatalogo.setValueAt(mat, fila, 0);
        tableItemCatalogo.setValueAt(precio, fila, 1);
        tableItemCatalogo.setValueAt(marca, fila, 2);
        txtMaterial.setText("");
        txtPrecio.setText("");
        txtMarca.setText("");
        fila++;
    }//GEN-LAST:event_btnAgregarTablaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dialogRecibirCatalgo.setVisible(false);
        dialogSucces.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        int j = 0;
        if (jTable1.getValueAt(0, 0) != null) {
            for (Material m : model.getDatos()) {
                if (jTable1.getValueAt(j, 6).equals(true)) {
                    datosComprar.add(m);
                    datosComprarM.add(m);
                }
                j++;
            }
            dialogRealizarPedidoOne.setVisible(true);
            dialogRealizarPedidoOne.setSize(800, 530);
            dialogRealizarPedidoOne.setTitle("Realizar Pedido a Proveedor");
            dialogRealizarPedidoOne.setResizable(false);
            dialogRealizarPedidoOne.setLocationRelativeTo(null);
            dialogRealizarPedido.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un material", "Information",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnPVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPVCActionPerformed
        // TODO add your handling code here:
        labelRubro.setText(btnPVC.getText());
        try {
            setTableProveedor(btnPVC.getText());
        } catch (DAOException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPVCActionPerformed

    private void btnFerreteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerreteriaActionPerformed
        // TODO add your handling code here:
        labelRubro.setText(btnFerreteria.getText());
        try {
            setTableProveedor(btnFerreteria.getText());
        } catch (DAOException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFerreteriaActionPerformed

    private void btnElectricidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElectricidadActionPerformed
        // TODO add your handling code here:
        labelRubro.setText(btnElectricidad.getText());
        try {
            setTableProveedor(btnElectricidad.getText());
        } catch (DAOException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnElectricidadActionPerformed

    private void btnConstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstruccionActionPerformed
        // TODO add your handling code here:
        labelRubro.setText(btnConstruccion.getText());
        try {
            setTableProveedor(btnConstruccion.getText());
        } catch (DAOException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConstruccionActionPerformed

    private void btnPintureriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPintureriaActionPerformed
        // TODO add your handling code here:
        labelRubro.setText(btnPintureria.getText());
        try {
            setTableProveedor(btnPintureria.getText());
        } catch (DAOException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPintureriaActionPerformed

    private void btnSiguienteRPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteRPOActionPerformed
        // TODO add your handling code here:
        int seleccion = tableProveedoresxRubro.getSelectedRow();
        if (seleccion == -1) {
            proveedorCompra = proveedores.get(seleccion);
            txtProveedorRPT.setText(proveedorCompra.getNombre());
            txtDireccionRPT.setText(proveedorCompra.getDireccion());
            txtTelefonoRPT.setText(String.valueOf(proveedorCompra.getTelefono()));
            setTablePedido();
            dialogRealizarPedidoTwo.setVisible(true);
            dialogRealizarPedidoTwo.setSize(800, 530);
            dialogRealizarPedidoTwo.setResizable(false);
            dialogRealizarPedidoTwo.setLocationRelativeTo(null);
            dialogRealizarPedidoTwo.setTitle("REalizar Pedido a Proveedor");
            dialogRealizarPedidoOne.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un proveedor", "Information",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSiguienteRPOActionPerformed

    private void btnAtrasRPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasRPOActionPerformed
        // TODO add your handling code here:
        datosComprarM.clear();
        dialogRealizarPedido.setVisible(true);
        dialogRealizarPedido.setTitle("Realizar Pedido a Proveedor");
        dialogRealizarPedido.setSize(800, 530);
        dialogRealizarPedido.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAtrasRPOActionPerformed

    private void btnAtrasRPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasRPTActionPerformed
        // TODO add your handling code here:
        dialogRealizarPedidoOne.setVisible(true);
        dialogRealizarPedidoOne.setSize(800, 530);
        dialogRealizarPedidoOne.setTitle("Realizar Pedido a Proveedor");
        dialogRealizarPedidoOne.setResizable(false);
        dialogRealizarPedidoOne.setLocationRelativeTo(null);
        dialogRealizarPedidoTwo.dispose();
    }//GEN-LAST:event_btnAtrasRPTActionPerformed

    private void btnGuardarRPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRPTActionPerformed
        try {
            // TODO add your handling code here:
            LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
            java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
            PedidoProveedor pedido = new PedidoProveedor(null, sqlDate, false, proveedorCompra.getCuit());
            try {
                manager.getPedidoProveedorDAO().insertar(pedido);
            } catch (DAOException ex) {
                Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
            }
            Long idP = pedido.getIdPedidoProveedor();
            int i = 0;
            for (Material m : datosComprarM) {
                int cant = (int) (tablePedidoFinal.getValueAt(i, 2));
                double subtotal = cant * m.getPrecioUnitario();
                DetallePedidoProveedor detalle = new DetallePedidoProveedor(
                        idP, m.getidMaterial(), m.getNombre() + " "
                        + m.getdescripcion(), cant, subtotal);
                detalle.setId(detalle.new Id(idP, m.getidMaterial()));
                try {
                    manager.getDetallePedidoProveedorDAO().insertar(detalle);
                } catch (DAOException ex) {
                    Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
                }
                i++;
            }
            datosComprar.clear();
            dialogRealizarPedidoTwo.dispose();
            JasperReport reporte = null;
            //String path = "src\\informes\\pedidoProveedorGenerado.jasper";
            Map parametro = new HashMap();
            parametro.put("idPedidoProveedor", idP);
            reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/informes/pedidoProveedorGenerado.jasper"));
//            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, manager.getConn());
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarRPTActionPerformed

    private void btnBuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPedidoActionPerformed

        // TODO add your handling code here:
        ////buscarPDF y mstrar
        if (validaciones.isNumber(txtNumeroPedido.getText())) {
            try {
                List<DetallePedidoProveedor> listDetalleProveedor = new ArrayList<>();
                Long idPedido = Long.valueOf(txtNumeroPedido.getText());
                PedidoProveedor pedido = manager.getPedidoProveedorDAO().obtener(idPedido);
                if (pedido != null) {
                    Long idP = pedido.getIdPedidoProveedor();
                    pedido.setEstado(true);
                    manager.getPedidoProveedorDAO().modificar(pedido);
                    listDetalleProveedor = manager.getDetallePedidoProveedorDAO().obtenerxPedido(pedido.getIdPedidoProveedor());
                    for (DetallePedidoProveedor d : listDetalleProveedor) {
                        Long id = d.getId().getIdMaterial();
                        Material m = manager.getMaterialDAO().obtener(id);
                        m.setStockMaterial(m.getStockMaterial() + d.getCantidad());
                        manager.getMaterialDAO().modificar(m);
                    }
                    JasperReport reporte = null;
                    //String path = "src\\informes\\pedidoProveedorGenerado.jasper";
                    Map parametro = new HashMap();
                    parametro.put("idPedidoProveedor", idP);
                    reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/informes/pedidoProveedorGenerado.jasper"));
                    //reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
                    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, manager.getConn());
                    JasperViewer view = new JasperViewer(jprint, false);
                    view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    view.setVisible(true);
                    dialogRecibirPedido.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Pedido inexistente", "Information",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (DAOException ex) {
                Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JRException ex) {
                Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Ingrese un numero de pedido valido", "Information",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarPedidoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        dialogSuccesPrint.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRecibirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecibirPedidoActionPerformed
        // TODO add your handling code here:
        dialogRecibirPedido.setVisible(true);
        dialogRecibirPedido.setTitle("Recibir Pedido");
        dialogRecibirPedido.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRecibirPedidoActionPerformed

    private void btnAtrasRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasRCActionPerformed
        // TODO add your handling code here:
        dialogRecibirCatalgo.dispose();
    }//GEN-LAST:event_btnAtrasRCActionPerformed

    private void btnAtrasROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasROActionPerformed
        // TODO add your handling code here:
        dialogRecibirPedido.dispose();
    }//GEN-LAST:event_btnAtrasROActionPerformed

    private void btnVerCatalogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCatalogosActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            proveedorCompra = proveedores.get(tableProveedoresxRubro.getSelectedRow());
            JasperReport reporte = null;
            Map parametro = new HashMap();
            parametro.put("cuit", proveedorCompra.getCuit());
            reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/informes/catalogo.jasper"));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, manager.getConn());
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerCatalogosActionPerformed

    public void setTablePedido() {

        tableProveedoresxRubro.removeAll();

        String[] columnas = new String[]{
            "Nombre",
            "Descripcion",
            "Cantidad"
        //"Seleccionar"
        };

        final Class[] tiposColumnas = new Class[]{
            java.lang.String.class,
            java.lang.String.class,
            java.lang.Integer.class, //JButton.class
        };
        Object[][] datos = new Object[datosComprar.size()][3];
        int i = 0;

        for (Material m : datosComprarM) {
            datos[i][0] = m.getNombre();
            datos[i][1] = m.getdescripcion();
            datos[i][2] = 0;
            i++;
        }
        tablePedidoFinal.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            Class[] tipos = tiposColumnas;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                return column == 2;
            }
        });

    }

    public void setTableProveedor(String rubro) throws DAOException {

///        tableProveedoresxRubro.removeRowSelectionInterval(0, tablePedidoFinal.getRowCount() - 1);
        String[] columnas = new String[]{
            "Cuit",
            "Nombre",
            "Telefono",
            "Direccion", //"Seleccionar"
        };

        final Class[] tiposColumnas = new Class[]{
            java.lang.Long.class,
            java.lang.String.class,
            java.lang.Long.class,
            java.lang.String.class, //JButton.class
        };

        proveedores = manager.getProveedorDAO().obtenerXrubros(rubro);
        Object[][] datos = new Object[proveedores.size()][5];
        int i = 0;
        for (Proveedor p : proveedores) {
            datos[i][0] = p.getCuit();
            datos[i][1] = p.getNombre();
            datos[i][2] = p.getTelefono();
            datos[i][3] = p.getDireccion();
            //datos[i][4] = new JButton("Seleccionar");
            i++;
        }
        tableProveedoresxRubro.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            Class[] tipos = tiposColumnas;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                return column == 4;
            }
        });
    }

    /**
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
//    public static void main(String args[]) throws SQLException {
//        DAOManager manager = new MySQLDaoManager("localhost", "root", "", "siac");
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            try {
//                new Compra(manager).setVisible(true);
//            } catch (DAOException ex) {
//                Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarTabla;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtrasC;
    private javax.swing.JButton btnAtrasRC;
    private javax.swing.JButton btnAtrasRO;
    private javax.swing.JButton btnAtrasRPO;
    private javax.swing.JButton btnAtrasRPT;
    private javax.swing.JButton btnBuscarPedido;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnConstruccion;
    private javax.swing.JButton btnElectricidad;
    private javax.swing.JButton btnFerreteria;
    private javax.swing.JButton btnGuardarRPT;
    private javax.swing.JButton btnPVC;
    private javax.swing.JButton btnPintureria;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnRealizarPedido;
    private javax.swing.JButton btnRecibirCatalogo;
    private javax.swing.JButton btnRecibirPedido;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnSiguienteRPO;
    private javax.swing.JButton btnVerCatalogos;
    private javax.swing.JDialog dialogRealizarPedido;
    private javax.swing.JDialog dialogRealizarPedidoOne;
    private javax.swing.JDialog dialogRealizarPedidoTwo;
    private javax.swing.JDialog dialogRecibirCatalgo;
    private javax.swing.JDialog dialogRecibirPedido;
    private javax.swing.JDialog dialogSucces;
    private javax.swing.JDialog dialogSuccesPrint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel labelRubro;
    private javax.swing.JTable tableItemCatalogo;
    private javax.swing.JTable tablePedidoFinal;
    private javax.swing.JTable tableProveedoresxRubro;
    private javax.swing.JTextField txtCuitRC;
    private javax.swing.JTextField txtDireccionP;
    private javax.swing.JTextField txtDireccionRPT;
    private javax.swing.JLabel txtInexistente;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProveedorRPT;
    private javax.swing.JTextField txtTelefonoRPT;
    // End of variables declaration//GEN-END:variables
}
