/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import MySQL.MySQLDaoManager;
import dao.DAOException;
import dao.DAOManager;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Cliente;
import modelo.DetallePedidoCliente;
import modelo.DetallePresupuesto;
import modelo.Material;
import modelo.PedidoCliente;
import modelo.Presupuesto;
import net.sf.jasperreports.engine.JasperReport;
import java.util.HashMap;
import javax.swing.JOptionPane;
import modelo.logUsuarios;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Lucas
 */
public class ventVenta extends javax.swing.JFrame {

    private static DAOManager manager;
    Cliente clientePedidoPresupuesto = null;
    List<DetallePresupuesto> listDetalle = new ArrayList<>();
    private List<Material> listamateriales = new ArrayList<>();
    private List<Material> listaseleccionados = new ArrayList<>();
    private int fila = 0;
    private float total = 0;
    private int mod;
    private int idUsuario;

    /**
     * Creates new form vtcompra
     */
    public ventVenta(DAOManager manager, int mod, int idUsuario) throws SQLException {
        ventVenta.manager = manager;
        initComponents();
        this.mod = mod;
        this.idUsuario = idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoVentaSinPresupuesto = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        ingresoidMaterial = new javax.swing.JTextField();
        botonBuscarMaterial = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaMaterialesPedidos = new javax.swing.JTable();
        agregarMaterialesSeleccionados = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaSeleccionados = new javax.swing.JTable();
        calcular = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dialogVentaSinPresupuestoOne = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        txtDniVSP = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DialogoGenerarPresupuesto = new javax.swing.JDialog();
        DialogoVentaConPresupuesto = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtIDPresupuesto = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        labelFailedPresupuesto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePresupuesto = new javax.swing.JTable();
        btnAtrasVentaPresupuesto = new javax.swing.JButton();
        btnSiguienteVentaPresupuesto = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dialogVentaConPresupuestoOne = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        btnSiguienteVPO = new javax.swing.JButton();
        txtDniCliente = new javax.swing.JTextField();
        btnAtrasVCPO = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        dialogVentaConPresupuestoTwo = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreClientePP = new javax.swing.JTextField();
        txtDniClientePP = new javax.swing.JTextField();
        txtDireccionClientePP = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePedidoPresupuesto = new javax.swing.JTable();
        btnAtrasVPT = new javax.swing.JButton();
        btnGenerarPedido = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        dialogFailed = new javax.swing.JDialog();
        dialogFailedCliente = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        dialogNotificarPedido = new javax.swing.JDialog();
        txtIdPedidoNotificar = new javax.swing.JTextField();
        btnNotificarPedido = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dialogSuccesNotificado = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        btnAceptarNP = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jTextArea4 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();

        DialogoVentaSinPresupuesto.getContentPane().setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Material: ");
        DialogoVentaSinPresupuesto.getContentPane().add(jLabel23);
        jLabel23.setBounds(30, 50, 60, 20);

        ingresoidMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoidMaterialActionPerformed(evt);
            }
        });
        DialogoVentaSinPresupuesto.getContentPane().add(ingresoidMaterial);
        ingresoidMaterial.setBounds(90, 50, 110, 30);

        botonBuscarMaterial.setText("Buscar");
        botonBuscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarMaterialActionPerformed(evt);
            }
        });
        DialogoVentaSinPresupuesto.getContentPane().add(botonBuscarMaterial);
        botonBuscarMaterial.setBounds(210, 50, 80, 30);

        tablaMaterialesPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaMaterialesPedidos);

        DialogoVentaSinPresupuesto.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(140, 90, 520, 158);

        agregarMaterialesSeleccionados.setText("Agregar");
        agregarMaterialesSeleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMaterialesSeleccionadosActionPerformed(evt);
            }
        });
        DialogoVentaSinPresupuesto.getContentPane().add(agregarMaterialesSeleccionados);
        agregarMaterialesSeleccionados.setBounds(670, 220, 80, 30);

        tablaSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Cantidad", "Precio Unitario", "Rubro", "Cantidad", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaSeleccionados);

        DialogoVentaSinPresupuesto.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(70, 260, 670, 149);

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        DialogoVentaSinPresupuesto.getContentPane().add(calcular);
        calcular.setBounds(670, 420, 100, 30);

        txttotal.setText("Total");
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        DialogoVentaSinPresupuesto.getContentPane().add(txttotal);
        txttotal.setBounds(500, 420, 160, 30);

        jButton10.setText("Siguiente");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        DialogoVentaSinPresupuesto.getContentPane().add(jButton10);
        jButton10.setBounds(670, 460, 100, 30);

        jButton11.setText("Atras");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        DialogoVentaSinPresupuesto.getContentPane().add(jButton11);
        jButton11.setBounds(40, 470, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Realizar Pedido");
        DialogoVentaSinPresupuesto.getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 10, 190, 40);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        DialogoVentaSinPresupuesto.getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 0, 800, 530);

        dialogVentaSinPresupuestoOne.getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dni Cliente: ");
        dialogVentaSinPresupuestoOne.getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 80, 30);
        dialogVentaSinPresupuestoOne.getContentPane().add(txtDniVSP);
        txtDniVSP.setBounds(150, 140, 100, 25);

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        dialogVentaSinPresupuestoOne.getContentPane().add(jButton5);
        jButton5.setBounds(260, 140, 90, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Realizar Pedido");
        dialogVentaSinPresupuestoOne.getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 29, 185, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogVentaSinPresupuestoOne.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 410, 310);

        javax.swing.GroupLayout DialogoGenerarPresupuestoLayout = new javax.swing.GroupLayout(DialogoGenerarPresupuesto.getContentPane());
        DialogoGenerarPresupuesto.getContentPane().setLayout(DialogoGenerarPresupuestoLayout);
        DialogoGenerarPresupuestoLayout.setHorizontalGroup(
            DialogoGenerarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        DialogoGenerarPresupuestoLayout.setVerticalGroup(
            DialogoGenerarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        DialogoVentaConPresupuesto.setSize(new java.awt.Dimension(800, 530));
        DialogoVentaConPresupuesto.getContentPane().setLayout(null);

        jScrollPane1.setViewportView(TxtIDPresupuesto);

        DialogoVentaConPresupuesto.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 92, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id Presupuesto:");
        DialogoVentaConPresupuesto.getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 100, 100, 20);

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        DialogoVentaConPresupuesto.getContentPane().add(jButton6);
        jButton6.setBounds(330, 93, 80, 30);
        DialogoVentaConPresupuesto.getContentPane().add(labelFailedPresupuesto);
        labelFailedPresupuesto.setBounds(0, 139, 0, 28);

        tablePresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre - Descripcion", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePresupuesto);

        DialogoVentaConPresupuesto.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(180, 140, 452, 290);

        btnAtrasVentaPresupuesto.setText("Atras");
        btnAtrasVentaPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasVentaPresupuestoActionPerformed(evt);
            }
        });
        DialogoVentaConPresupuesto.getContentPane().add(btnAtrasVentaPresupuesto);
        btnAtrasVentaPresupuesto.setBounds(40, 450, 59, 23);

        btnSiguienteVentaPresupuesto.setText("Siguiente");
        btnSiguienteVentaPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteVentaPresupuestoActionPerformed(evt);
            }
        });
        DialogoVentaConPresupuesto.getContentPane().add(btnSiguienteVentaPresupuesto);
        btnSiguienteVentaPresupuesto.setBounds(690, 450, 90, 23);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Venta con Presupuesto");
        DialogoVentaConPresupuesto.getContentPane().add(jLabel14);
        jLabel14.setBounds(260, 30, 280, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        DialogoVentaConPresupuesto.getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 800, 530);

        dialogVentaConPresupuestoOne.getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dni Cliente: ");
        dialogVentaConPresupuestoOne.getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 110, 80, 20);

        btnSiguienteVPO.setText("Generar Pedido");
        btnSiguienteVPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteVPOActionPerformed(evt);
            }
        });
        dialogVentaConPresupuestoOne.getContentPane().add(btnSiguienteVPO);
        btnSiguienteVPO.setBounds(150, 150, 140, 23);

        txtDniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniClienteActionPerformed(evt);
            }
        });
        dialogVentaConPresupuestoOne.getContentPane().add(txtDniCliente);
        txtDniCliente.setBounds(180, 110, 100, 25);

        btnAtrasVCPO.setText("Atras");
        btnAtrasVCPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasVCPOActionPerformed(evt);
            }
        });
        dialogVentaConPresupuestoOne.getContentPane().add(btnAtrasVCPO);
        btnAtrasVCPO.setBounds(40, 200, 59, 23);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogVentaConPresupuestoOne.getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 400, 300);

        dialogVentaConPresupuestoTwo.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pedido");
        dialogVentaConPresupuestoTwo.getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 10, 124, 44);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre: ");
        dialogVentaConPresupuestoTwo.getContentPane().add(jLabel9);
        jLabel9.setBounds(164, 64, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dni:");
        dialogVentaConPresupuestoTwo.getContentPane().add(jLabel10);
        jLabel10.setBounds(319, 64, 40, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Direccion: ");
        dialogVentaConPresupuestoTwo.getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 70, 70, 20);

        txtNombreClientePP.setEditable(false);
        dialogVentaConPresupuestoTwo.getContentPane().add(txtNombreClientePP);
        txtNombreClientePP.setBounds(220, 60, 90, 30);

        txtDniClientePP.setEditable(false);
        dialogVentaConPresupuestoTwo.getContentPane().add(txtDniClientePP);
        txtDniClientePP.setBounds(350, 60, 80, 30);

        txtDireccionClientePP.setEditable(false);
        txtDireccionClientePP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionClientePPActionPerformed(evt);
            }
        });
        dialogVentaConPresupuestoTwo.getContentPane().add(txtDireccionClientePP);
        txtDireccionClientePP.setBounds(500, 60, 130, 30);

        tablePedidoPresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre - Descripcion", "Precio Unitario", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablePedidoPresupuesto);

        dialogVentaConPresupuestoTwo.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(180, 110, 452, 330);

        btnAtrasVPT.setText("Atras");
        btnAtrasVPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasVPTActionPerformed(evt);
            }
        });
        dialogVentaConPresupuestoTwo.getContentPane().add(btnAtrasVPT);
        btnAtrasVPT.setBounds(40, 440, 59, 23);

        btnGenerarPedido.setText("Generar Pedido");
        btnGenerarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPedidoActionPerformed(evt);
            }
        });
        dialogVentaConPresupuestoTwo.getContentPane().add(btnGenerarPedido);
        btnGenerarPedido.setBounds(657, 440, 130, 23);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogVentaConPresupuestoTwo.getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 800, 530);

        javax.swing.GroupLayout dialogFailedLayout = new javax.swing.GroupLayout(dialogFailed.getContentPane());
        dialogFailed.getContentPane().setLayout(dialogFailedLayout);
        dialogFailedLayout.setHorizontalGroup(
            dialogFailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        dialogFailedLayout.setVerticalGroup(
            dialogFailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        dialogFailedCliente.getContentPane().setLayout(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cliente Inexistente");
        dialogFailedCliente.getContentPane().add(jLabel17);
        jLabel17.setBounds(130, 80, 140, 40);

        jButton8.setText("Aceptar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        dialogFailedCliente.getContentPane().add(jButton8);
        jButton8.setBounds(160, 130, 73, 23);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogFailedCliente.getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 400, 300);

        dialogNotificarPedido.getContentPane().setLayout(null);

        txtIdPedidoNotificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPedidoNotificarActionPerformed(evt);
            }
        });
        dialogNotificarPedido.getContentPane().add(txtIdPedidoNotificar);
        txtIdPedidoNotificar.setBounds(130, 140, 130, 25);

        btnNotificarPedido.setText("Notificar");
        btnNotificarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificarPedidoActionPerformed(evt);
            }
        });
        dialogNotificarPedido.getContentPane().add(btnNotificarPedido);
        btnNotificarPedido.setBounds(270, 140, 73, 23);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Id Pedido:");
        dialogNotificarPedido.getContentPane().add(jLabel19);
        jLabel19.setBounds(50, 145, 70, 20);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogNotificarPedido.getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 400, 300);

        dialogSuccesNotificado.getContentPane().setLayout(null);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Notificado con Exito");
        dialogSuccesNotificado.getContentPane().add(jLabel21);
        jLabel21.setBounds(100, 50, 140, 30);

        btnAceptarNP.setText("Aceptar");
        btnAceptarNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarNPActionPerformed(evt);
            }
        });
        dialogSuccesNotificado.getContentPane().add(btnAceptarNP);
        btnAceptarNP.setBounds(120, 110, 71, 23);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        dialogSuccesNotificado.getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 0, 300, 200);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Venta sin presupuesto");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 180, 150, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Venta con presupuesto");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 180, 160, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Generar presupuesto");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 180, 140, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Venta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 60, 110, 64);

        jButton4.setText("Atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 310, 59, 23);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(340, 180, 140, 40);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        getContentPane().add(jTextArea2);
        jTextArea2.setBounds(10, 180, 150, 40);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        getContentPane().add(jTextArea3);
        jTextArea3.setBounds(170, 180, 160, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 102, 102));
        jButton7.setText("Clientes");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(270, 250, 160, 40);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        getContentPane().add(jTextArea4);
        jTextArea4.setBounds(270, 250, 160, 40);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(102, 102, 102));
        jButton9.setText("Notificar Pedido");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(80, 250, 160, 40);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        getContentPane().add(jTextArea5);
        jTextArea5.setBounds(80, 250, 160, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogoVentaSinPresupuesto.setVisible(true);
        DialogoVentaSinPresupuesto.setResizable(false);
        DialogoVentaSinPresupuesto.setTitle("Venta sin presupuesto");
        DialogoVentaSinPresupuesto.setSize(800, 530);
        DialogoVentaSinPresupuesto.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DialogoVentaConPresupuesto.setTitle("Ventana con Presupuesto");
        DialogoVentaConPresupuesto.setVisible(true);
        DialogoVentaConPresupuesto.setResizable(false);
        DialogoVentaConPresupuesto.setSize(800, 530);
        DialogoVentaConPresupuesto.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            vtnPresupuesto ventanaVenta;
            ventanaVenta = new vtnPresupuesto(manager);
            ventanaVenta.setTitle("Generar Presupuesto");
            ventanaVenta.setVisible(true);
            ventanaVenta.setSize(800, 530);
            ventanaVenta.setResizable(false);
            ventanaVenta.setLocationRelativeTo(null);
            DialogoGenerarPresupuesto.setTitle("Generar Presupuesto");

        } catch (DAOException ex) {
            Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        home ventaHome;
        try {
            ventaHome = new home(mod, idUsuario);
            ventaHome.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (validaciones.isNumber(TxtIDPresupuesto.getText())) {
            LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
            java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
            Long ID = Long.valueOf(TxtIDPresupuesto.getText());
            Presupuesto p = null;
            try {
                p = manager.getPresupuestoDAO().obtener(ID);
            } catch (DAOException ex) {
                Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (p == null) {
                labelFailedPresupuesto.setText("Presupuesto Inexistente");
            } else {
                int dias = (int) ((sqlDate.getTime() - p.getFecha().getTime()) / 86400000);
                if (dias > 30) {
                    labelFailedPresupuesto.setText("Presupuesto sin validez");
                } else {
                    try {
                        listDetalle = manager.getDetallePresupuestoDAO().obtenerXIdPresupuesto(p.getIdPresupuesto());
                    } catch (DAOException ex) {
                        Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    setTablePresupuesto(listDetalle);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un ID Presupuesto valido", "Information", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSiguienteVentaPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteVentaPresupuestoActionPerformed
        // TODO add your handling code here:
        if (tablePresupuesto.getValueAt(0, 0) != null) {
            dialogVentaConPresupuestoOne.setVisible(true);
            dialogVentaConPresupuestoOne.setSize(400, 300);
            dialogVentaConPresupuestoOne.setLocationRelativeTo(null);
            dialogVentaConPresupuestoOne.setTitle("Venta con Presupuesto");
        }
    }//GEN-LAST:event_btnSiguienteVentaPresupuestoActionPerformed

    private void txtDniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniClienteActionPerformed

    private void btnSiguienteVPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteVPOActionPerformed
        if (validaciones.isNumber(txtDniCliente.getText())) {
            Long dni = Long.valueOf(txtDniCliente.getText());
            try {
                clientePedidoPresupuesto = manager.getClienteDAO().obtener(dni);
            } catch (DAOException ex) {
                Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (clientePedidoPresupuesto == null) {
                dialogFailedCliente.setTitle("Agregar Cliente");
                dialogFailedCliente.setLocationRelativeTo(null);
                dialogFailedCliente.setSize(400, 300);
                dialogFailedCliente.setVisible(true);
            } else {
                generarPresupuesto();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI valido", "Information", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSiguienteVPOActionPerformed

    private void generarPresupuesto() {
        dialogVentaConPresupuestoTwo.setVisible(true);
        dialogVentaConPresupuestoTwo.setSize(800, 530);
        dialogVentaConPresupuestoTwo.setLocationRelativeTo(null);
        dialogVentaConPresupuestoTwo.setTitle("Venta con Presupuesto");
        DialogoVentaConPresupuesto.setVisible(false);
        dialogVentaConPresupuestoOne.setVisible(false);
        txtNombreClientePP.setText(clientePedidoPresupuesto.getNombre());
        txtDireccionClientePP.setText(clientePedidoPresupuesto.getDireccion());
        txtDniClientePP.setText(String.valueOf(clientePedidoPresupuesto.getTelefono()));
        setTablePedidoPresupuesto();
    }

    private void btnGenerarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPedidoActionPerformed
        try {
            // TODO add your handling code here:
//            LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
//            java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
            Timestamp sqlDate = new Timestamp(System.currentTimeMillis());
            double total = 0;
            logUsuarios log = new logUsuarios((long) idUsuario, sqlDate, "Generar Pedido", 0L);
            for (DetallePresupuesto dp : listDetalle) {
                total = total + dp.getSubtotal();
            }
            PedidoCliente pedido = new PedidoCliente(null, "En espera", total,
                    sqlDate, sqlDate, clientePedidoPresupuesto.getdni(), log.getId());
            try {
                manager.getPedidoClienteDAO().insertar(pedido);
            } catch (DAOException ex) {
                Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
            Long idPC = pedido.getIdPedidoCliente();
            for (DetallePresupuesto dp : listDetalle) {
                DetallePedidoCliente nuevo = new DetallePedidoCliente(
                        idPC, dp.getId().getIdMaterial(), dp.getDescripcion(),
                        (float) dp.getSubtotal(), dp.getCantidad());
                try {
                    manager.getDetallePedidoDAO().insertar(nuevo);
                    Material m = manager.getMaterialDAO().obtener(dp.getId().getIdMaterial());
                    m.setStockMaterial(m.getStockMaterial() - dp.getCantidad());
                    manager.getMaterialDAO().modificar(m);
                } catch (DAOException ex) {
                    Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            JasperReport reporte = null;
//            String path = "src\\informes\\pedidoGenerado.jasper";
            Map parametro = new HashMap();
            parametro.put("idPedidoCliente", idPC);
            reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/informes/pedidoGenerado.jasper"));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, manager.getConn());
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
            log.setIdAccion(idPC);
            try {
                manager.getLogDAO().modificar(log);
            } catch (DAOException ex) {
                Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (JRException ex) {
            Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarPedidoActionPerformed

    private void txtDireccionClientePPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionClientePPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionClientePPActionPerformed

    private void btnAtrasVCPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasVCPOActionPerformed
        // TODO add your handling code here:
        DialogoVentaConPresupuesto.setTitle("Ventana Sin Presupuesto");
        DialogoVentaConPresupuesto.setVisible(true);
        DialogoVentaConPresupuesto.setResizable(false);
        DialogoVentaConPresupuesto.setSize(800, 530);
        DialogoVentaConPresupuesto.setLocationRelativeTo(null);
        dialogVentaConPresupuestoOne.setVisible(false);
    }//GEN-LAST:event_btnAtrasVCPOActionPerformed

    private void btnAtrasVPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasVPTActionPerformed
        // TODO add your handling code here:
        dialogVentaConPresupuestoOne.setVisible(true);
        dialogVentaConPresupuestoOne.setSize(400, 300);
        dialogVentaConPresupuestoOne.setLocationRelativeTo(null);
        dialogVentaConPresupuestoOne.setTitle("Venta son Presupuesto");
        dialogVentaConPresupuestoTwo.setVisible(false);
    }//GEN-LAST:event_btnAtrasVPTActionPerformed

    private void btnAtrasVentaPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasVentaPresupuestoActionPerformed
        // TODO add your handling code here:
        DialogoVentaConPresupuesto.setVisible(false);
    }//GEN-LAST:event_btnAtrasVentaPresupuestoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        vtnCliente vtn = new vtnCliente(manager);
        vtn.setVisible(true);
        vtn.setSize(500, 400);
        vtn.setTitle("Agregar Cliente");
        vtn.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dialogVentaConPresupuestoOne.dispose();
        dialogVentaConPresupuestoTwo.dispose();
        dialogFailedCliente.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        dialogNotificarPedido.setVisible(true);
        dialogNotificarPedido.setLocationRelativeTo(null);
        dialogNotificarPedido.setSize(400, 300);
        dialogNotificarPedido.setTitle("Notificar Pedido");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtIdPedidoNotificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPedidoNotificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPedidoNotificarActionPerformed

    private void btnNotificarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificarPedidoActionPerformed

        if (validaciones.isNumber(txtIdPedidoNotificar.getText())) {
//            LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
//            java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
            Timestamp sqlDate = new Timestamp(System.currentTimeMillis());
            try {
                // TODO add your handling code here:
                Long idPedido = Long.valueOf(txtIdPedidoNotificar.getText());
                PedidoCliente pedido = manager.getPedidoClienteDAO().obtener(idPedido);
                if (pedido != null) {
                    if (!pedido.getEstadoPedidoC().equals("Entregado")) {
                        pedido.setEstadoPedidoC("Entregado");
                        pedido.setFechaRecibido(sqlDate);
                        manager.getPedidoClienteDAO().modificar(pedido);
                        dialogSuccesNotificado.setVisible(true);
                        dialogSuccesNotificado.setTitle("Notificado");
                        dialogSuccesNotificado.setSize(300, 200);
                        dialogSuccesNotificado.setLocationRelativeTo(null);
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Pedido ya notificado", "Information",
                                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Ingrese un ID Pedido valido", "Information",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (DAOException ex) {
                Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un ID Pedido valido",
                    "Information", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnNotificarPedidoActionPerformed

    private void btnAceptarNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarNPActionPerformed
        // TODO add your handling code here:
        dialogNotificarPedido.setVisible(false);
        dialogSuccesNotificado.setVisible(false);
    }//GEN-LAST:event_btnAceptarNPActionPerformed

    private void ingresoidMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoidMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoidMaterialActionPerformed

    private void botonBuscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarMaterialActionPerformed
        String material;
        material = ingresoidMaterial.getText();
        if (validaciones.isString(material)) {
            try {
                listamateriales = manager.getMaterialDAO().obtenerTodosxNombre(material);//cambiar obtener todo por nombre
                setTablaMaterialesPedidos();
            } catch (DAOException ex) {
                Logger.getLogger(vtnPresupuesto.class.getName()).log(Level.SEVERE, null, ex);

            }
        }
    }//GEN-LAST:event_botonBuscarMaterialActionPerformed

    public void setTablaMaterialesPedidos() {

        tablaMaterialesPedidos.removeAll();

        String[] columnas = new String[]{
            "Nombre",
            "Descripcion",
            "Cantidad",
            "Precio Unitario",
            "Rubro"
        //"Seleccionar"
        };
        final Class[] tiposColumnas = new Class[]{
            java.lang.String.class,
            java.lang.String.class,
            java.lang.Integer.class,
            java.lang.Float.class,
            java.lang.String.class
//JButton.class
        };
        Object[][] datos = new Object[listamateriales.size()][5];
        int i = 0;

        for (Material m : listamateriales) {
            datos[i][0] = m.getNombre();
            datos[i][1] = m.getdescripcion();
            datos[i][2] = m.getStockMaterial();
            datos[i][3] = m.getPrecioUnitario();
            datos[i][4] = m.getRubro();
            i++;
        }

//        datos[0][0]= mat.getNombre();
//        datos[0][1]= mat.getdescripcion();
//        datos[0][2]= mat.getStockMaterial();
//        datos[0][3]= mat.getPrecioUnitario();
//        datos[0][4]= mat.getRubro();
        tablaMaterialesPedidos.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            Class[] tipos = tiposColumnas;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                return false;
            }
        });

    }

    private void agregarMaterialesSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMaterialesSeleccionadosActionPerformed

        int seleccionado = tablaMaterialesPedidos.getSelectedRow();
        Material m = listamateriales.get(seleccionado);
        listaseleccionados.add(m);
        tablaSeleccionados.setValueAt(m.getNombre(), fila, 0);
        tablaSeleccionados.setValueAt(m.getdescripcion(), fila, 1);
        tablaSeleccionados.setValueAt(m.getStockMaterial(), fila, 2);
        tablaSeleccionados.setValueAt(m.getPrecioUnitario(), fila, 3);
        tablaSeleccionados.setValueAt(m.getRubro(), fila, 4);

        fila++;

    }//GEN-LAST:event_agregarMaterialesSeleccionadosActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        int tamaño = tablaSeleccionados.getRowCount();
        total = 0;
        Long sum = 0l;
        int i;
        for (i = 0; i < tamaño; i++) {
            Material m = listaseleccionados.get(i);
            int cantidad = Integer.valueOf(tablaSeleccionados.getValueAt(i, 5).toString());
            if (m.getStockMaterial() > cantidad) {
                sum = Long.valueOf(tablaSeleccionados.getValueAt(i, 3).toString()) * cantidad;
                tablaSeleccionados.setValueAt(sum, i, 6);
            } else {
                tablaSeleccionados.setValueAt("Stock disponible " + m.getStockMaterial(), i, 6);
            }

            if (tablaSeleccionados.getValueAt(i + 1, i) == null) {
                i = tamaño + 1;
            }
            total = total + sum;
        }
        txttotal.setText("$" + total);
    }//GEN-LAST:event_calcularActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
        java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
        Presupuesto Pre = new Presupuesto(null, sqlDate, total);
        try {
            manager.getPresupuestoDAO().insertar(Pre);
        } catch (DAOException ex) {
            Logger.getLogger(vtnPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
        }
        Long idpre = Pre.getIdPresupuesto();
        int i = 0;
        for (Material m : listaseleccionados) {

            Long subtotal = Long.valueOf(tablaSeleccionados.getValueAt(i, 6).toString());
            Integer cantidad = Integer.valueOf(tablaSeleccionados.getValueAt(i, 5).toString());
            DetallePresupuesto nuevo = new DetallePresupuesto(idpre, m.getidMaterial(), m.getNombre() + " " + m.getdescripcion(), subtotal, cantidad);
            i++;
            try {
                manager.getDetallePresupuestoDAO().insertar(nuevo);
            } catch (DAOException ex) {
                Logger.getLogger(vtnPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        dialogVentaSinPresupuestoOne.setVisible(true);
        dialogVentaSinPresupuestoOne.setSize(400, 300);
        dialogVentaSinPresupuestoOne.setTitle("Realizar Pedido");

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        DialogoVentaSinPresupuesto.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (validaciones.isNumber(txtDniVSP.getText())) {
            try {
                Long dni = Long.valueOf(txtDniVSP.getText());
                Cliente c = manager.getClienteDAO().obtener(dni);
                if (c != null) {
//                    LocalDate todayLocalDate = LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires"));
//                    java.sql.Date sqlDate = java.sql.Date.valueOf(todayLocalDate);
                    Timestamp sqlDate = new Timestamp(System.currentTimeMillis());
                    logUsuarios log = new logUsuarios((long) idUsuario, sqlDate, "Generar Pedido", 0L);
                    PedidoCliente p = new PedidoCliente(null, "En espera",
                            (double) total, sqlDate, sqlDate, c.getdni(), log.getId());
                    try {
                        manager.getPedidoClienteDAO().insertar(p);
                    } catch (DAOException ex) {
                        Logger.getLogger(vtnPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Long idpre = p.getIdPedidoCliente();
                    int i = 0;
                    for (Material m : listaseleccionados) {
                        Long subtotal = Long.valueOf(tablaSeleccionados.getValueAt(i, 6).toString());
                        Integer cantidad = Integer.valueOf(tablaSeleccionados.getValueAt(i, 5).toString());
                        DetallePedidoCliente nuevo = new DetallePedidoCliente(idpre, m.getidMaterial(), m.getNombre() + " " + m.getdescripcion(), subtotal, cantidad);
                        m.setStockMaterial(m.getStockMaterial() - cantidad);
                        try {
                            manager.getMaterialDAO().modificar(m);
                            manager.getDetallePedidoDAO().insertar(nuevo);
                        } catch (DAOException ex) {
                            Logger.getLogger(vtnPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JasperReport reporte = null;
//                    String path = "src\\informes\\pedidoGenerado.jasper";
                        Map parametro = new HashMap();
                        parametro.put("idPedidoCliente", idpre);
                        reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/informes/pedidoGenerado.jasper"));
                        JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, manager.getConn());
                        JasperViewer view = new JasperViewer(jprint, false);
                        view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                        view.setVisible(true);
                        log.setIdAccion(idpre);
                        manager.getLogDAO().modificar(log);
                    }
                } else {
                    vtnCliente vtn = new vtnCliente(manager);
                    vtn.setVisible(true);
                    vtn.setSize(500, 400);
                    vtn.setTitle("Agregar Cliente");
                    vtn.setLocationRelativeTo(null);
                }
            } catch (DAOException ex) {
                Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JRException ex) {
                Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
            DialogoVentaSinPresupuesto.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un dni valido", "Information", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        //dialogVentaSinPresupuestoOne.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void setTablePedidoPresupuesto() {
        tablePedidoPresupuesto.removeAll();
        String[] columnas = new String[]{
            "Nombre - Descripcion",
            //"Precio Unitario",
            "Cantidad",
            "Subtotal"
        //"Seleccionar"
        };

        final Class[] tiposColumnas = new Class[]{
            java.lang.String.class,
            int.class,
            java.lang.Long.class, //JButton.class
        };
        Object[][] datos = new Object[listDetalle.size()][3];
        int i = 0;

        for (DetallePresupuesto m : listDetalle) {
            datos[i][0] = m.getDescripcion();
            datos[i][1] = m.getCantidad();
            datos[i][2] = m.getSubtotal();
            //datos[i][3] = m.getPrecioUnitario(); Mantenimiento
            i++;
        }
        tablePedidoPresupuesto.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            Class[] tipos = tiposColumnas;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                return false;
            }
        });
    }

    private void setTablePresupuesto(List<DetallePresupuesto> listDetalle) {
        tablePresupuesto.removeAll();

        String[] columnas = new String[]{
            "Nombre - Descripcion",
            "Cantidad",
            "Subtotal"
        //"Seleccionar"
        };

        final Class[] tiposColumnas = new Class[]{
            java.lang.String.class,
            int.class,
            java.lang.Long.class, //JButton.class
        };
        Object[][] datos = new Object[listDetalle.size()][3];
        int i = 0;

        for (DetallePresupuesto m : listDetalle) {
            datos[i][0] = m.getDescripcion();
            datos[i][1] = m.getCantidad();
            datos[i][2] = m.getSubtotal();
            i++;
        }
        tablePresupuesto.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            Class[] tipos = tiposColumnas;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                return false;
            }
        });
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ventVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ventVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ventVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ventVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new ventVenta(manager).setVisible(true);
//                } catch (SQLException ex) {
//                    Logger.getLogger(ventVenta.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogoGenerarPresupuesto;
    private javax.swing.JDialog DialogoVentaConPresupuesto;
    private javax.swing.JDialog DialogoVentaSinPresupuesto;
    private javax.swing.JTextPane TxtIDPresupuesto;
    private javax.swing.JButton agregarMaterialesSeleccionados;
    private javax.swing.JButton botonBuscarMaterial;
    private javax.swing.JButton btnAceptarNP;
    private javax.swing.JButton btnAtrasVCPO;
    private javax.swing.JButton btnAtrasVPT;
    private javax.swing.JButton btnAtrasVentaPresupuesto;
    private javax.swing.JButton btnGenerarPedido;
    private javax.swing.JButton btnNotificarPedido;
    private javax.swing.JButton btnSiguienteVPO;
    private javax.swing.JButton btnSiguienteVentaPresupuesto;
    private javax.swing.JButton calcular;
    private javax.swing.JDialog dialogFailed;
    private javax.swing.JDialog dialogFailedCliente;
    private javax.swing.JDialog dialogNotificarPedido;
    private javax.swing.JDialog dialogSuccesNotificado;
    private javax.swing.JDialog dialogVentaConPresupuestoOne;
    private javax.swing.JDialog dialogVentaConPresupuestoTwo;
    private javax.swing.JDialog dialogVentaSinPresupuestoOne;
    private javax.swing.JTextField ingresoidMaterial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JLabel labelFailedPresupuesto;
    private javax.swing.JTable tablaMaterialesPedidos;
    private javax.swing.JTable tablaSeleccionados;
    private javax.swing.JTable tablePedidoPresupuesto;
    private javax.swing.JTable tablePresupuesto;
    private javax.swing.JTextField txtDireccionClientePP;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtDniClientePP;
    private javax.swing.JTextField txtDniVSP;
    private javax.swing.JTextField txtIdPedidoNotificar;
    private javax.swing.JTextField txtNombreClientePP;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
