/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import MySQL.MySQLDaoManager;
import dao.DAOManager;
import java.sql.SQLException;
import vistas.home;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author leori
 */
public class vtnInformes extends javax.swing.JFrame {

    private final DAOManager manager;
    int mod;
    
    public vtnInformes(DAOManager manager, int mod) {
        this.manager = manager;
        initComponents();
        this.mod = mod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPedidoCliente = new javax.swing.JButton();
        btnPedidoProveedor = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 166, 44);

        btnPedidoCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnPedidoCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPedidoCliente.setForeground(new java.awt.Color(0, 153, 204));
        btnPedidoCliente.setText("Pedidos de Cliente");
        btnPedidoCliente.setBorder(null);
        btnPedidoCliente.setBorderPainted(false);
        btnPedidoCliente.setContentAreaFilled(false);
        btnPedidoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedidoCliente);
        btnPedidoCliente.setBounds(270, 170, 160, 50);

        btnPedidoProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnPedidoProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPedidoProveedor.setForeground(new java.awt.Color(0, 153, 204));
        btnPedidoProveedor.setText("Pedidos por Proveedor");
        btnPedidoProveedor.setBorder(null);
        btnPedidoProveedor.setBorderPainted(false);
        btnPedidoProveedor.setContentAreaFilled(false);
        btnPedidoProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedidoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedidoProveedor);
        btnPedidoProveedor.setBounds(90, 170, 160, 50);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        jTextArea1.setRows(5);
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(90, 170, 160, 50);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        getContentPane().add(jTextArea3);
        jTextArea3.setBounds(270, 170, 164, 50);

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 320, 59, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundHome.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoProveedorActionPerformed
        try {
            JasperReport reporte = null;
//            String path = "src\\informes\\pedidoRealizadosProveedor.jasper";
            reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/informes/pedidoRealizadosProveedor.jasper"));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, manager.getConn());
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(vtnInformes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPedidoProveedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            home vtnHome = new home(mod);
            vtnHome.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(vtnInformes.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPedidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoClienteActionPerformed
        try {
            JasperReport reporte = null;
//            String path = "src\\informes\\estadosPedidosClientes.jasper";
            reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/informes/estadosPedidosClientes.jasper"));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, manager.getConn());
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(vtnInformes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPedidoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) throws SQLException {
//        DAOManager manager = new MySQLDaoManager("localhost", "root", "", "siac");
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vtnInformes(manager).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedidoCliente;
    private javax.swing.JButton btnPedidoProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
